name: forest_map
description: Forest Map a Bioverse App.

publish_to: "none"
version: 2.3.0+3.20231002

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  easy_mask: ^2.0.1
  bot_toast: ^4.1.3
  easy_localization: ^3.0.3
  get_it: ^7.6.4
  image_picker: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  connectivity_plus: ^5.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  data_connection_checker_nulls: ^0.0.2
  image: ^4.1.3
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  app_settings: ^5.1.1
  share_plus: ^7.2.1
  geojson: ^1.0.0
  http: ^1.1.0
  geoflutterfire2: ^2.3.15
  sqflite: ^2.3.0
  path: ^1.8.3
  proximity_hash: ^2.0.0
  flutter_swiper_view: ^1.1.8

  # Firebase Deps
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  firebase_storage: ^11.5.2
  firebase_dynamic_links: ^5.4.5
  cloud_firestore: ^4.13.2
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  mockito: ^5.4.3
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - translations/en.json
    - translations/pt-BR.json
    - assets/
    - assets/example_images/
    - google_fonts/
