name: forestMapApp
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^0.5.33
  provider: ^4.3.2+3
  easy_mask: ^1.1.4
  bot_toast: ^3.0.5
  easy_localization: ^2.3.3

  # Firebase Deps
  firebase_core: "0.5.3"
  firebase_auth: "^0.18.4"
  cloud_firestore: "^0.14.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - translations/en.json
    - translations/pt-BR.json
