name: forest_map_app
description: A new Flutter project.

publish_to: "none"
version: 1.2.1+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.1
  google_fonts: ^2.0.0
  provider: ^5.0.0
  easy_mask: ^1.1.4
  bot_toast: ^4.0.1
  easy_localization: ^3.0.0
  get_it: ^6.0.0
  image_picker: ^0.7.3
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  geolocator: ^7.0.1
  connectivity: ^3.0.2
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  data_connection_checker: ^0.3.4
  image: ^3.0.1
  uuid: ^3.0.1
  cached_network_image: ^3.0.0-nullsafety
  app_settings: ^4.0.4
  share: ^2.0.1
  geojson: ^0.10.0
  http: ^0.13.0
  geoflutterfire: ^3.0.0-nullsafety.1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  proximity_hash: ^1.1.0
  flutter_swiper: ^1.1.6

  # Firebase Deps
  firebase_core: "^1.10.0"
  firebase_auth: "^1.0.1"
  firebase_storage: "^8.0.0"
  firebase_dynamic_links: ^0.8.0
  cloud_firestore: "^2.5.4"
  google_sign_in: ^5.0.1
  flutter_facebook_auth: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: ^1.10.9
  mockito: ^5.0.2
  faker: ^2.0.0-rc.2

flutter:
  uses-material-design: true

  assets:
    - translations/en.json
    - translations/pt-BR.json
    - assets/
    - assets/example_images/
    - google_fonts/
