name: forest_map
description: Forest Map a Bioverse App.

publish_to: "none"
version: 2.1.0+27092023

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.1
  google_fonts: ^4.0.4
  provider: ^6.0.5
  easy_mask: ^2.0.1
  bot_toast: ^4.0.1
  easy_localization: ^3.0.0
  get_it: ^7.6.0
  image_picker: ^1.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  geolocator: ^9.0.2
  connectivity: ^3.0.2
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  data_connection_checker_nulls: ^0.0.2
  image: ^4.0.17
  uuid: ^3.0.1
  cached_network_image: ^3.0.0-nullsafety
  app_settings: ^4.0.4
  share: ^2.0.1
  geojson: ^1.0.0
  http: ^0.13.0
  geoflutterfire2: ^2.3.15
  sqflite: ^2.0.0+3
  path: ^1.8.0
  proximity_hash: ^2.0.0
  flutter_swiper_view: ^1.1.8

  # Firebase Deps
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  firebase_dynamic_links: ^5.3.5
  cloud_firestore: ^4.9.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^5.0.11
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  mockito: ^5.0.2
  faker: ^2.0.0-rc.2

flutter:
  uses-material-design: true

  assets:
    - translations/en.json
    - translations/pt-BR.json
    - assets/
    - assets/example_images/
    - google_fonts/
    - shorebird.yaml
