// Mocks generated by Mockito 5.4.0 from annotations
// in forest_map/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i9;

import 'package:data_connection_checker_nulls/data_connection_checker_nulls.dart'
    as _i15;
import 'package:forest_map/core/adapters/hive_adapter.dart' as _i16;
import 'package:forest_map/core/enums/social_login_types.dart' as _i6;
import 'package:forest_map/core/platform/network_info.dart' as _i14;
import 'package:forest_map/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i4;
import 'package:forest_map/features/organization/data/datasources/organization_local_data_source.dart'
    as _i12;
import 'package:forest_map/features/organization/data/models/organization_model.dart'
    as _i13;
import 'package:forest_map/features/organization/domain/entities/organization.dart'
    as _i8;
import 'package:forest_map/features/user/data/datasource/user_local_data_source.dart'
    as _i10;
import 'package:forest_map/features/user/data/datasource/user_remote_data_source.dart'
    as _i7;
import 'package:forest_map/features/user/data/models/user_model.dart' as _i2;
import 'package:forest_map/features/user/domain/entities/user.dart' as _i11;
import 'package:hive/hive.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHiveInterface_1 extends _i1.SmartFake implements _i3.HiveInterface {
  _FakeHiveInterface_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserModel> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);
  @override
  _i5.Future<_i2.UserModel> signInWithSocial(_i6.SocialLoginType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithSocial,
          [type],
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #signInWithSocial,
            [type],
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);
  @override
  _i5.Future<_i2.UserModel> signUp(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            name,
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #signUp,
            [
              name,
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);
  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> forgotPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i7.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserModel> getUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [id],
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #getUser,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);
  @override
  _i5.Future<_i2.UserModel> updateUser({
    required String? id,
    String? name,
    String? email,
    List<_i8.Organization>? organizations,
    _i9.File? avatar,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {
            #id: id,
            #name: name,
            #email: email,
            #organizations: organizations,
            #avatar: avatar,
          },
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #updateUser,
            [],
            {
              #id: id,
              #name: name,
              #email: email,
              #organizations: organizations,
              #avatar: avatar,
            },
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i10.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserModel?> getUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [id],
        ),
        returnValue: _i5.Future<_i2.UserModel?>.value(),
      ) as _i5.Future<_i2.UserModel?>);
  @override
  _i5.Future<void> saveUser({
    String? id,
    _i11.User? user,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [],
          {
            #id: id,
            #user: user,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [OrganizationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrganizationLocalDataSource extends _i1.Mock
    implements _i12.OrganizationLocalDataSource {
  MockOrganizationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i13.OrganizationModel?> getOrganization(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganization,
          [id],
        ),
        returnValue: _i5.Future<_i13.OrganizationModel?>.value(),
      ) as _i5.Future<_i13.OrganizationModel?>);
  @override
  _i5.Future<void> saveOrganization({
    String? id,
    _i8.Organization? organization,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOrganization,
          [],
          {
            #id: id,
            #organization: organization,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i14.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> get isWifi => (super.noSuchMethod(
        Invocation.getter(#isWifi),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Stream<_i15.DataConnectionStatus> get connectionStatusStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatusStream),
        returnValue: _i5.Stream<_i15.DataConnectionStatus>.empty(),
      ) as _i5.Stream<_i15.DataConnectionStatus>);
}

/// A class which mocks [HiveAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveAdapter<T> extends _i1.Mock implements _i16.HiveAdapter<T> {
  MockHiveAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get boxName => (super.noSuchMethod(
        Invocation.getter(#boxName),
        returnValue: '',
      ) as String);
  @override
  _i3.HiveInterface get hive => (super.noSuchMethod(
        Invocation.getter(#hive),
        returnValue: _FakeHiveInterface_1(
          this,
          Invocation.getter(#hive),
        ),
      ) as _i3.HiveInterface);
  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<T?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i5.Future<T?>.value(),
      ) as _i5.Future<T?>);
  @override
  Iterable<dynamic> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);
  @override
  _i5.Future<void> put(
    String? id,
    T? payload,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            id,
            payload,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
